In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'color' : ['red','blue','green','green','red','blue']
})

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
lbl_encoder = LabelEncoder()

In [6]:
import numpy as np

In [7]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\jaisw\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [3]:
from sklearn.preprocessing import OrdinalEncoder

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame({
    'size' : ['small','medium','large','medium','small','large']
})

In [6]:
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [7]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [8]:
encoder.transform([['small']])

c:\Users\jaisw\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

In [14]:
import pandas as pd

df = pd.DataFrame({
    'city' : ['New York','London','Paris','Tokyo','New York','Paris'],
    'price' : [200,150,300,350,100,250]
})

In [15]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    350
4  New York    100
5     Paris    250

In [17]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [18]:
mean_price

{'London': 150.0, 'New York': 150.0, 'Paris': 275.0, 'Tokyo': 350.0}

In [19]:
df['city_encoded'] = df['city'].map(mean_price)

In [20]:
df

       city  price  city_encoded
0  New York    200         150.0
1    London    150         150.0
2     Paris    300         275.0
3     Tokyo    350         350.0
4  New York    100         150.0
5     Paris    250         275.0

In [22]:
df[['price','city_encoded']]

   price  city_encoded
0    200         150.0
1    150         150.0
2    300         275.0
3    350         350.0
4    100         150.0
5    250         275.0